using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Praedium.Core
{
    public enum Glyph
    {
        #region Control Characters (0 - 31)

        None,
        StartOfHeader,
        StartOfText,
        EndOfText,
        EndOfTransmission,
        Enquiry,
        Acknowledge,
        Bell,
        Backspace,
        HorizontalTabulation,
        LineFeed,
        VerticalTabulation,
        FormFeed,
        CarriageReturn,
        ShiftOut,
        ShiftIn,
        DataLinkEscape,
        DeviceControl1,
        DeviceControl2,
        DeviceControl3,
        DeviceControl4,
        NegativeAcknowledge,
        SynchronousIdle,
        EndOfTransmissionBlock,
        Cancel,
        EndOfMedium,
        Substitute,
        Escape,
        FileSeparator,
        GroupSeparator,
        RecordSeparator,
        UnitSeparator,

        #endregion

        #region Standard Character Set (32 - 127)

        Space,
        ExclamationMark,
        DoubleQuotationMark,
        Hash,
        Dollar,
        Percent,
        Ampersand,
        Apostrophe,
        ParenthesisOpen,
        ParenthesisClose,
        Asterisk,
        Plus,
        Comma,
        Dash,
        Period,
        Slash,
        Zero,
        One,
        Two,
        Three,
        Four,
        Five,
        Six,
        Seven,
        Eight,
        Nine,
        Colon,
        Semicolon,
        LessThan,
        Equals,
        GreaterThan,
        QuestionMark,
        At,
        AUpper,
        BUpper,
        CUpper,
        DUpper,
        EUpper,
        FUpper,
        GUpper,
        HUpper,
        IUpper,
        JUpper,
        KUpper,
        LUpper,
        MUpper,
        NUpper,
        OUpper,
        PUpper,
        QUpper,
        RUpper,
        SUpper,
        TUpper,
        UUpper,
        VUpper,
        WUpper,
        XUpper,
        YUpper,
        ZUpper,
        BracketOpen,
        BackSlash,
        BracketClose,
        Caret,
        Underscore,
        GraveAccent,
        ALower,
        BLower,
        CLower,
        DLower,
        ELower,
        FLower,
        GLower,
        HLower,
        ILower,
        JLower,
        KLower,
        LLower,
        MLower,
        NLower,
        OLower,
        PLower,
        QLower,
        RLower,
        SLower,
        TLower,
        ULower,
        VLower,
        WLower,
        XLower,
        YLower,
        ZLower,
        OpenBrace,
        Pipe,
        CloseBrace,
        Tilde,
        Delete,

        #endregion

        #region Extended Character Set (128 - 255)

        CCedillaUpper,
        UDiaeresisLower,
        EAcuteLower,
        ACircumflexLower,
        ADiaeresisLower,
        AAccentLower,
        ARingLower,
        CCedillaLower,
        ECircumflexLower,
        EDiaeresisLower,
        EAccentLower,
        IDiaeresisLower,
        ICircumflexLower,
        IAccentLower,
        ADiaeresisUpper,
        ARingUpper,
        EAcuteUpper,
        AELower,
        AEUpper,
        OCircumflexLower,
        ODiaeresisLower,
        OAccentLower,
        UCircumflexLower,
        UAccentLower,
        YDiaeresisLower,
        ODiaeresisUpper,
        UDiaeresisUpper,
        Cent,
        Pound,
        Yen,
        Peseta,
        FHookLower,
        AAcuteLower,
        IAcuteLower,
        OAcuteLower,
        UAcuteLower,
        NTildeLower,
        NTildeUpper,
        OrdinalFeminine,
        OrdinalMasculine,
        QuotationMarkInverted,
        ReversedNot,
        Not,
        OneHalf,
        OneQuarter,
        ExclamationMarkInverted,
        LeftPointingDoubleAngleQuotation,
        RightPointingDoubleAngleQuotation,

        LightShade,
        MediumShade,
        DarkShade,

        BoxSingleUpDown,
        BoxSingleLeftUpDown,
        BoxDoubleLeftSingleUpDown,
        BoxSingleLeftDoubleUpDown,
        BoxSingleLeftDoubleDown,
        BoxDoubleLeftSingleDown,
        BoxDoubleLeftUpDown,
        BoxDoubleUpDown,
        BoxDoubleLeftDown,
        BoxDoubleLeftUp,
        BoxSingleLeftDoubleUp,
        BoxDoubleLeftSingleUp,
        BoxSingleLeftDown,
        BoxSingleUpRight,
        BoxSingleLeftUpRight,
        BoxSingleLeftRightDown,
        BoxSingleUpRightDown,
        BoxSingleLeftRight,
        BoxSingleFull,
        BoxSingleUpDownDoubleRight,
        BoxDoubleUpDownSingleRight,
        BoxDoubleUpRight,
        BoxDoubleRightDown,
        BoxDoubleLeftUpRight,
        BoxDoubleLeftRightDown,
        BoxDoubleUpRightDown,
        BoxDoubleLeftRight,
        BoxDoubleFull,
        BoxDoubleLeftRightSingleUp,
        BoxSingleLeftRightDoubleUp,
        BoxDoubleLeftRightSingleDown,
        BoxSingleLeftRightDoubleDown,
        BoxDoubleUpSingleRight,
        BoxSingleUpDoubleRight,
        BoxDoubleRightSingleDown,
        BoxSingleRightDoubleDown,
        BoxSingleLeftRightDoubleUpDown,
        BoxDoubleLeftRightSingleUpDown,
        BoxSingleLeftUp,
        BoxSingleRightDown,
        FullBlock,
        LowerHalfBlock,
        LeftHalfBlock,
        RightHalfBlock,
        UpperHalfBlock,

        AlphaLower,
        SharpSLower,
        GammaUpper,
        PiLower,
        SigmaUpper,
        SigmaLower,
        Micro,
        Tau,
        PhiUpper,
        ThetaUpper,
        OmegaUpper,
        DeltaLower,
        Infinity,
        PhiLower,
        EpsilonLower,
        Intersection,
        IdenticalTo,
        PlusMinus,
        GreatherThanEqual,
        LowerThanEqual,
        TopHalfIntegral,
        LowerHalfIntegral,
        Division,
        AlmostEqual,
        Degree,
        Bullet,
        MiddleDot,
        SquareRoot,
        SuperScriptNLower,
        SuperScriptTwo,
        BlackSquare,
        NoBreakSpace,

        #endregion

        #region Custom Mappings

        Character = StartOfHeader,
        CharacterInversed = StartOfText,

        Heart = EndOfText,
        Diamond = EndOfTransmission,
        Club = Enquiry,
        Spade = Acknowledge,

        Circle = Bell,
        CircleInversed = Backspace,

        Oval = HorizontalTabulation,
        OvalInversed = LineFeed,

        Mars = VerticalTabulation,
        Venus = FormFeed,

        Note = CarriageReturn,
        BarNote = ShiftOut,

        Sun = ShiftIn,
        Star = Asterisk,

        Prompt = SynchronousIdle,
        
        TriangleLeft = DeviceControl1,
        TraingleUp = RecordSeparator,
        TriangleRight = DataLinkEscape,
        TriangleDown = UnitSeparator,

        DoubleExclamationMark = DeviceControl3,

        ArrowUpDown = DeviceControl2,
        ArrowUpDownUnderline = EndOfTransmissionBlock,
        ArrowLeftRight = GroupSeparator,
        ArrowLeft = Escape,
        ArrowUp = Cancel,
        ArrowRight = Substitute,
        ArrowDown = EndOfMedium,

        FishLeft = LeftPointingDoubleAngleQuotation,
        FishRight = RightPointingDoubleAngleQuotation,

        Pebble = MiddleDot,
        Stone = Bullet,
        StoneBig = Circle,
        Boulder = Diamond,

        Bubble1 = MiddleDot,
        Bubble2 = Bullet,
        BubblePop = Oval,

        Flower = Sun

        #endregion
    }
}
